### ISSUE TITLE
xsi:schemaLocation declaration causes validation problems with xerces

### ISSUE THREAD

**Issue by porosnie** [aixm/donlon-outdated-#16]
The current xsi:schemaLocation includes explicitly the gml, gmd and xlink schema locations. This is not necessary, since they are already imported in the AIXM and basicMessage schema. In addition, xerces reports a validation error - duplicate declaration of elements in the gml namespace.
A shorter schemaLocation declaration would be sufficient:

"xsi:schemaLocation="http://www.aixm.aero/schema/5.1/message http://www.aixm.aero/schema/5.1/message/AIXM_BasicMessage.xsd http://www.aixm.aero/schema/5.1/event http://www.aixm.aero/schema/5.1/event/Event_Features.xsd"

If you agree, could someone create a Pull request with this change?

**Comment by vog** [comment]
That makes a lot of sense to me, so here is the pull request.

**Comment by porosnie** [comment]
Could we have the support of someone else for this, so that we can commit?
